name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log in to GitLab Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.hzdr.de/l.kulla/kaapana-build-bvm/
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Extract commit SHA
      run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Build and push Docker image with 'latest' tag
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          registry.hzdr.de/l.kulla/kaapana-build-bvm/kaapana-persistence-importer:0.0.0-latest
          registry.hzdr.de/l.kulla/kaapana-build-bvm/kaapana-persistence-importer:${{ env.COMMIT_SHA }}

